
name: MACHINEKAM
channels:
  - javascript
#   - fragcolor
#   - r
dependencies:
#   - r
#   - r-essentials
#   - r-base
  - nodejs
#   - pandas
#   - pytorch
#   - torchvision
#   - nimtorch
#   - tensorflow
